import React, { createContext, useContext, useEffect, useState, useCallback } from 'react';
import {
  DEFAULT_DISPLAY_TIMEZONE,
  formatInDisplayTimeZone,
  formatDateShortInDisplayTimeZone,
  formatFileTimestampInDisplayTimeZone,
} from '@/app/lib/displayTimeZone';

type Language = 'es' | 'en';
type Theme = 'light' | 'dark';
type TempUnit = 'C' | 'F';

interface SettingsContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  tempUnit: TempUnit;
  toggleTempUnit: () => void;
  /** IANA, p. ej. Etc/GMT+5 (visualización GMT-5; datos de referencia por defecto). */
  displayTimeZone: string;
  setDisplayTimeZone: (iana: string) => void;
  formatDateTime: (input: string | number | Date | null | undefined, withSeconds?: boolean) => string;
  /** dd/MM + HH:mm en el huso (sin año), p. ej. columnas de tabla. */
  formatDateShort: (input: string | number | Date | null | undefined) => string;
  formatFileTimestamp: (input?: string | number | Date) => string;
  convertTemp: (celsius: number) => number;
  formatTemp: (celsius: number) => string;
  t: (key: string, replacements?: Record<string, string> | string) => string;
}

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'dashboard': 'Panel de Control',
    'control': 'Control de Dispositivos',
    'monitoring': 'Monitoreo y Análisis',
    'processes': 'Seguimiento (Plus)',
    'control_module_menu': 'Procesos de control (panel)',
    'recipes': 'Recetas (Plus)',
    'users': 'Usuarios (Plus)',
    'settings': 'Configuración',
    'help': 'Manual de Usuario',
    'logout': 'Cerrar Sesión',
    'profile': 'Mi Perfil',
    'operator': 'Operador',
    'search_placeholder': 'Buscar dispositivo...',
    'search_process_placeholder': 'Buscar por cliente, lote o producto...',

    // Login
    'welcome_back': 'Bienvenido de nuevo',
    'enter_credentials': 'Ingresa tus credenciales para acceder al panel de control',
    'password': 'Contraseña',
    'login_button': 'Iniciar Sesión',
    'login_subtitle': 'Sistema de gestión y monitoreo en tiempo real para soluciones refrigeradas de ZGROUP.',
    'configuring': 'Configurando...',
    'init_admin': 'Inicializar cuenta Admin (Dev)',
    'session_success': 'Sesión iniciada correctamente',
    'admin_ready': 'Cuenta administrativa lista',
    'login_error': 'Error al iniciar sesión',
    'email_label': 'Correo Electrónico',

    // Dashboard
    'active_units': 'Unidades Activas',
    'active_alarms': 'Alarmas Activas',
    'completed_processes': 'Procesos Completados',
    'processes_in_progress': 'Procesos en curso',
    'alarms_numero_sum_hint': 'Σ número alarma (API)',
    'processes_in_progress_hint': 'Sin contar Manual',
    'total_consumption': 'Consumo Total',
    'fleet_status': 'Estado de Flota',
    'executive_summary': 'Resumen ejecutivo',
    'download_executive_summary': 'Descargar resumen ejecutivo (PDF)',
    'of_total': 'De {{total}} total',
    'require_attention': 'Requieren atención',
    'this_week': 'Esta semana',
    'historical_accumulated': 'Acumulado histórico',
    'units_online': 'Unidades en línea',
    'device': 'Unidad',
    'last_data': 'Último dato',
    'online': 'En línea',
    'wait': 'Espera',
    'offline': 'Desconectado',
    'connection': 'Conexión',
    'equipment': 'Equipo',
    'error_loading_devices': 'Error al cargar dispositivos',

    // Device Detail
    'device_not_found': 'Dispositivo no encontrado',
    'operation': 'Operación',
    'analysis': 'Análisis',
    'current_process_status': 'Estado del Proceso Actual',
    'status_current_title': 'Estatus actual',
    'status_show_more': 'Ver más',
    'status_show_less': 'Ver menos',
    'status_temp_supply': 'T° Suministro',
    'status_return': 'T° Retorno',
    'status_ethylene': 'Nivel etileno',
    'status_alarms': 'Mensajes',
    'status_ventilation': 'Ventilación',
    'status_humidity': 'Nivel humedad',
    'status_co2': 'Nivel CO₂',
    'status_capacity': 'Potencia (%)',
    'status_evap': 'T° Evaporador',
    'status_cond': 'T° Condensador',
    'status_compressor': 'T° Compresor',
    'status_ambient': 'T° Externa',
    'status_cargo_n': 'T° Sensor {{n}}',
    'status_line_voltage': 'Voltaje máquina',
    'status_line_frequency': 'Frecuencia máquina',
    'status_phase_n': 'Fase {{n}}',
    'status_sp_co2': 'SP CO₂',
    'status_kwh': 'Consumo eléctrico',
    'status_gas_exchange': 'Intercambio de gases',
    'status_sp_ethylene': 'SP etileno',
    'vent_na': 'N/D',
    'cfm_unit': 'CFM',
    'sp_ethyleno_unit': 'ppm',
    'gas_ex_off': 'Desactivado',
    'gas_ex_manual': 'Manual',
    'gas_ex_auto': 'Automático',
    'temp_unit_hint': 'Unidad (°C/°F):',
    'timezone_display_label': 'Hora (referencia)',
    'timezone_data_hint': 'Los datos de telemetría se interpretan y muestran en el huso elegido. Por defecto GMT-5. Cambie a GMT-4, GMT-6, México, etc. según su criterio.',
    'tz_reference_gmt5': 'GMT-5 (referencia por defecto)',
    'tz_gmt4': 'GMT-4',
    'tz_gmt5': 'GMT-5',
    'tz_gmt6': 'GMT-6',
    'tz_gmt7': 'GMT-7',
    'tz_gmt8': 'GMT-8',
    'tz_gmt3': 'GMT-3',
    'tz_mexico_city': 'México (oficial)',
    'tz_bogota': 'Colombia',
    'tz_lima': 'Perú',
    'tz_utc': 'UTC (referencia)',
    'operational_data': 'Datos Operacionales',
    'no_active_process': 'No hay proceso activo',
    'power_consumption': 'Consumo Energía',
    'energy_consumption_period': 'Consumo de energía (período)',
    'total_accumulated': 'Total Acumulado',
    'defrost_interval': 'Intervalo Defrost',
    'evaporation_coil': 'Bobina Evaporación',
    'recipe': 'Receta',
    'phase': 'Fase',
    'start': 'Inicio',
    'end': 'Fin',
    'estimated_end': 'Fin Estimado',
    'back': 'Volver',
    'historical_data': 'Datos Históricos',
    'historical_data_table': 'Datos en tabla',
    'last_12_hours': 'Últimas 12 Horas',
    'last_12h_no_data_title': 'No hay datos en las últimas 12 horas',
    'last_12h_no_data_madurador': 'No hay series de temperatura (aire retorno), humedad, etileno (campo_1) ni dióxido de carbono (co2_reading) en el periodo. Si en origen `cantidad_datos` es 0, aún no hay histórico.',
    'preset_last12': 'Últimas 12 h',
    'preset_basic': 'Básico (Temp, HR, Etileno, CO₂)',
    'preset_temperatures': 'Solo temperaturas',
    'preset_gases': 'Gases y humedad',
    'preset_full': 'Completo',
    'columns_to_show': 'Columnas a mostrar',
    'search_by_date': 'Buscar por fecha',

    // Control Panel
    'manual_mode': 'Manual',
    'homogenization': 'Homogenización',
    'ripening': 'Maduración',
    'ventilation': 'Ventilación',
    'cooling': 'Enfriamiento',
    'process_integral': 'Proceso integral / automático',
    'process_manual_name': 'Manual',
    'process_unknown': 'Proceso',
    'fleet_process_panel': 'Proceso (panel de control)',
    'device_status': 'Estado del Equipo',
    'equipo_estado_actual': 'Estado actual del equipo',
    'controls_available_when_on': 'Los controles de temperatura, humedad y gases están disponibles con el equipo encendido.',
    'climatization': 'Climatización',
    'target_temperature': 'Temperatura Objetivo',
    'relative_humidity': 'Humedad Relativa',
    'gases_ventilation': 'Gases y Ventilación',
    'ethylene_injection': 'Inyección Etileno',
    'ventilation_speed': 'Velocidad Ventilación',
    'apply_changes': 'Aplicar Cambios',
    'confirm_changes': 'Confirmar Cambios',
    'applying': 'Aplicando...',
    'confirm_changes_desc': 'Se aplicarán los siguientes cambios en el dispositivo:',
    'environmental_conditions': 'Condiciones Ambientales',
    'target_co2': 'CO2 Objetivo',
    'duration': 'Duración',
    'preview': 'Previsualización',
    'start_process': 'Iniciar Proceso',
    'starting': 'Iniciando...',
    'cancel': 'Cancelar',
    'final_temperature': 'Temperatura Final',
    'estimated_duration': 'Duración Estimada',
    'co2_limit': 'Límite CO2',
    'process_time': 'Tiempo de Proceso',
    'max_duration': 'Duración Máxima',
    'cooling_ramp': 'Rampa de Enfriamiento',

    // Process List
    'process_tracking': 'Seguimiento de Procesos',
    'process_tracking_desc': 'Gestione lotes activos, historial y nuevos servicios.',
    'new_process': 'Nuevo Proceso',
    'filters': 'Filtros',
    'in_process': 'EN PROCESO',
    'attention': 'ATENCIÓN',
    'current_phase': 'Fase Actual',
    'estimated_progress': 'Progreso Estimado',
    'view_details': 'Ver Detalles',
    'start_new_process': 'Iniciar Nuevo Proceso',
    'start_new_process_desc': 'Configure un nuevo lote y asigne una receta de maduración.',
    'process_data_mgmt': 'Gestión de datos',
    'process_data_mgmt_desc': 'Listado de procesos guardados: consultar, abrir o eliminar.',
    'no_saved_processes': 'Aún no hay procesos guardados.',
    'confirm_delete_process': '¿Eliminar este proceso? No se podrá deshacer.',
    'process_name_col': 'Nombre',
    'client': 'Cliente',
    'created': 'Creado',
    'action_delete': 'Eliminar',
    'loading': 'Cargando…',
    'saving_process': 'Guardando…',
    'load_processes_error': 'Error al cargar los procesos.',
    'seguimiento': 'Seguimiento',
    'field_process_name': 'Proceso',
    'device_active_check_loading': 'Comprobando si el equipo ya tiene un proceso en curso…',
    'device_active_process_title': 'Este dispositivo ya tiene un proceso activo',
    'device_active_process_body':
      'Solo un proceso a la vez puede quedar activo en este equipo. Puede abrir el proceso actual desde la lista, pero no añadir más muestreos si se cancela. Al continuar, el proceso en curso pasará a estado CANCELADO (se conserva para trazabilidad) y el nuevo será el activo.',
    'device_active_ack_replace':
      'Entiendo y deseo continuar: se cancelará el proceso en curso vinculado a este dispositivo y el nuevo reemplazará a ese. No se podrán registrar más muestreos en el proceso cancelado.',
    'status_ripening_cancelled': 'CANCELADO',
    'process_cancelled_info':
      'Proceso cancelado: la información y la bitácora se conservan para trazabilidad. No se admiten nuevos muestreos.',
    'sampling_forbidden_cancelled': 'No se pueden añadir muestreos a un proceso cancelado.',
    'process_not_active_generic': 'Este proceso no está en estado activo; no se pueden registrar nuevos muestreos.',

    // Informe de seguimiento / final
    'report_title_interim': 'Reporte de seguimiento',
    'report_title_final': 'Informe final de maduración',
    'report_subtitle_active': 'Resumen de muestreos y evolución de parámetros hasta la fecha.',
    'report_subtitle_closed': 'Proceso finalizado: historial completo de muestreos y tendencias.',
    'report_subtitle_cancelled': 'Proceso cancelado: se conserva la trazabilidad de muestreos y parámetros registrados.',
    'report_final_banner_title': 'Informe final disponible',
    'report_final_banner_desc':
      'Consulte el informe con todos los muestreos y la evolución de Brix, firmeza y color. Puede imprimirlo o guardarlo como PDF desde el navegador.',
    'report_open_interim': 'Reporte de seguimiento',
    'report_open_final': 'Ver informe final',
    'report_section_process': 'Datos del proceso',
    'report_section_samplings': 'Muestreos registrados',
    'report_section_evolution': 'Evolución de parámetros',
    'report_field_id': 'ID',
    'report_recipe': 'Receta',
    'report_targets': 'Metas (receta)',
    'report_started': 'Inicio',
    'report_estimated_end': 'Fin estimado',
    'report_col_date': 'Fecha y hora',
    'report_col_type': 'Tipo / título',
    'report_col_person': 'Responsable',
    'report_col_params': 'Parámetros medidos',
    'report_col_notes': 'Observaciones',
    'report_no_samplings': 'No hay muestreos registrados en la bitácora.',
    'report_evolution_note': 'Valores numéricos por índice de muestreo (orden cronológico). Líneas omiten puntos sin dato.',
    'report_param_brix': 'Brix (°)',
    'report_param_firmness': 'Firmeza',
    'report_param_color': 'Color',
    'report_param_firmness_short': 'Firmeza',
    'report_param_color_short': 'Color',
    'report_x_axis': 'Muestreo n.º',
    'report_no_numeric_params':
      'No hay valores numéricos reconocibles (Brix / firmeza / color) para dibujar la gráfica. Los datos siguen listados en la tabla.',
    'report_generated_at': 'Generado:',
    'report_close': 'Cerrar',
    'report_print': 'Imprimir / PDF',

    // Create Process Form
    'new_maturation_process': 'Nuevo Proceso de Maduración',
    'new_process_desc': 'Ingrese los datos del lote y configure los parámetros iniciales.',
    'client_info': 'Información del Cliente',
    'client_type': 'Tipo de Cliente',
    'client_name': 'Nombre del Cliente / Empresa',
    'batch_details': 'Detalles del Lote',
    'product': 'Producto',
    'quantity_kg': 'Cantidad (kg)',
    'control_device': 'Dispositivo Control',
    'recipe_planning': 'Receta y Planificación',
    'select_recipe_library': 'Seleccionar Receta de Biblioteca',
    'create_edit_custom': 'Crear/Editar Personalizada',
    'process_display_name': 'Nombre del proceso (opcional)',
    'process_name_auto_hint': 'Si lo deja vacío, se generará: Producto + Cliente/Empresa + Dispositivo + Fecha (día/mes/año).',
    'client_type_external': 'Servicio externo',
    'client_type_internal': 'Propio / interno',
    'lot_origin': 'Procedencia / lote',
    'lot_origin_ph': 'Finca, región, nota de lote…',
    'batch_volume_m3': 'Volumen del lote (m³, opcional)',
    'no_device': 'sin dispositivo',
    'loading_devices': 'Cargando dispositivos…',
    'control_device_list_hint': 'Misma flota que en el panel de control. Incluye equipos apagados; se asume encendido al iniciar el proceso.',
    'select_device_placeholder': '— Elegir dispositivo de control —',
    'estado': 'Estado',
    'estado_on': 'Encendido',
    'estado_off': 'Apagado',
    'humidity_set_point_label': 'Set humedad (HR)',
    'set_point_co2_label': 'Set CO₂',
    'set_temp_label': 'Set temperatura',
    'control_device_off_note': 'Si el equipo está apagado, se entenderá que se encenderá al iniciar el proceso.',
    'select_product_first_for_recipes': 'Elija primero un producto del catálogo; las recetas se filtrarán por ese producto (como en la biblioteca de recetas).',
    'no_recipes_for_product': 'No hay recetas en catálogo para este producto. Puede crear una receta personalizada.',
    'select_recipe_option': '— Elegir receta —',
    'custom_recipe_current': 'Receta personalizada actual',
    'process_start_time': 'Fecha/hora de inicio del proceso',
    'start_now_button': 'Ahora mismo',
    'start_schedule_label': 'Programar inicio',
    'target_objectives_title': 'Parámetros objetivo',
    'no_objectives_check': 'No establecer objetivos',
    'objectives_optional': 'Opcional. Indique metas de calidad si aplica.',
    'new_param_name_placeholder': 'Nombre del parámetro',
    'unit_custom': 'pers.',
    'initial_sampling_block_title': 'Muestreo inicial (recepción)',
    'initial_sampling_block_desc': 'Mismos criterios que «Registrar muestreo» — solo tipo Inicial / recepción. Parámetros y fotos opcionales; observaciones obligatorias.',
    'sampling_type_initial_only': 'Inicial / recepción',
    'sampling_notes': 'Observaciones de muestreo',
    'sampling_notes_ph': 'Condición del fruto, anomalías…',
    'sampling_observations_required': 'Las observaciones del muestreo inicial son obligatorias (registro de seguimiento).',
    'sampling_photo_evidence': 'Evidencia fotográfica',
    'sampling_photos_optional': 'Una o varias imágenes, opcionales. Vista previa local hasta confirmar el proceso.',
    'sampling_register': 'Registrar muestreo',
    'sampling_save': 'Guardar muestreo',
    'sampling_person_field': 'Persona que realiza el muestreo',
    'sampling_person_ph': 'Nombre y apellido / quien toma la muestra',
    'sampling_person_field_hint': 'Por defecto su usuario. Puede corregirlo; en el registro se guarda también el usuario de sesión que envía el formulario.',
    'sampling_executed_by': 'Muestreo realizado por',
    'registered_in_system': 'Registrado en el sistema (usuario de sesión)',
    'sampling_photos_multi_hint': 'Varias imágenes: puede elegir varias a la vez o añadir en varias pasadas. Opcional. JPG, PNG.',
    'field_supervisor': 'Supervisor de proceso',
    'process_supervisor_title': 'Supervisor de proceso (obligatorio)',
    'process_supervisor_desc': 'Responsable de la supervisión del lote. Por defecto se rellena con su cuenta; puede editarlo.',
    'supervisor_name': 'Nombre del supervisor',
    'supervisor_email_optional': 'Correo del supervisor (opcional)',
    'supervisor_required': 'Indique el nombre del supervisor de proceso.',
    'sampling_person_required': 'Indique la persona que realiza el muestreo inicial.',
    'initial_sampling_person': 'Persona que realiza el muestreo inicial',
    'initial_sampling_person_ph': 'Quien registra el muestreo de recepción',
    'initial_sampling_person_hint': 'Por defecto su nombre; se puede cambiar. El sistema guarda quién envía el registro (usuario conectado).',
    'sampling_remove_photo': 'Quitar foto',
    'sampling_result_tracking_note': 'Este muestreo se guarda como registro de seguimiento del proceso. Solo las observaciones son obligatorias.',
    'sampling_params_all_optional': 'Los parámetros medidos son opcionales.',
    'back_to_process_list': 'Volver a la lista de procesos',
    'process_recipe_total_hours': 'Duración total (suma de fases de la receta): {{hours}} h',
    'process_estimated_end': 'Fin aproximado del proceso: {{date}}',

    // Users
    'user_management': 'Gestión de Usuarios',
    'new_user': 'Nuevo Usuario',
    'system_users': 'Usuarios del Sistema',
    'user': 'Usuario',
    'email': 'Email',
    'role': 'Rol',
    'status': 'Estado',
    'actions': 'Acciones',
    'edit': 'Editar',
    'edit_user': 'Editar usuario',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'full_name': 'Nombre completo',
    'delete': 'Eliminar',
    'delete_user': 'Eliminar usuario',
    'confirm_delete_user': '¿Dar de baja a {{name}}? El usuario dejará de mostrarse en el listado (baja lógica).',
    'user_created': 'Usuario creado',
    'user_updated': 'Usuario actualizado',
    'user_deleted': 'Usuario dado de baja',
    'error_users': 'Error al cargar usuarios',
    'no_users_yet': 'No hay usuarios. Cree el primero con «Nuevo usuario».',
    'duplicate_email': 'Ya existe un usuario activo con ese correo',
    'role_admin': 'Administrador',
    'role_operator': 'Operador',
    'role_viewer': 'Visualizador',
    'role_superadmin': 'Super administrador',
    'company_field': 'Empresa',
    'company_placeholder': 'Vacío = «sin empresa»',
    'identificador_field': 'Identificador empresa (Madurador)',
    'identificador_field_short': 'Id. empresa',
    'identificador_placeholder': 'Ej. 1001',
    'identificador_hint': 'Opcional. Con valor, el panel carga dispositivos desde la API Madurador para ese identificador.',
    'madurador_reference_title': 'Referencia equipo (Madurador)',
    'madurador_detail_estado': 'Estado equipo',
    'madurador_detail_supply': 'Suministro (temp.)',
    'madurador_detail_return': 'Retorno',
    'madurador_detail_evap': 'Evaporador',
    'madurador_detail_cond': 'Condensador',
    'madurador_detail_compressor': 'Compresor',
    'madurador_detail_avl': 'Ventilación (avl / CFM)',
    'madurador_detail_voltage': 'Voltaje línea',
    'madurador_detail_set_co2': 'Set CO₂',
    'madurador_detail_set_hum': 'Set humedad',
    'madurador_detail_capacity': 'Carga compresor %',
    'madurador_last_on': 'Última fecha encendido',
    'madurador_last_sample': 'Última muestra telemetría',
    'madurador_until': 'Datos hasta',
    'madurador_process_start': 'Inicio proceso',
    'madurador_fecha_procesada': 'Última corrida (procesada)',
    'photo_label': 'Foto de perfil',
    'photo_choose_file': 'Elegir imagen',
    'photo_change_file': 'Cambiar imagen',
    'photo_remove_selection': 'Quitar selección',
    'photo_preview_hint': 'Vista previa. La imagen se subirá al guardar.',
    'photo_current_hint': 'Foto actual en el servidor.',
    'password_new_user': 'Contraseña',
    'password_required_new': 'Indique una contraseña para el nuevo usuario',
    'password_change_hint': 'Nueva contraseña',
    'password_optional_placeholder': 'Dejar vacío para no cambiar',
    
    // Status
    'status_active': 'Activo',
    'status_warning': 'Advertencia',
    'status_alarm': 'Alarma',
    'status_offline': 'Fuera de Línea',
    'status_standby': 'En Espera',
    'status_powered_on': 'Encendido',
    'status_powered_off': 'Apagado',
    'completed': 'Completado',
    'turn_on': 'Encender',
    'turn_off': 'Apagar',
    'device_on': 'Dispositivo Encendido',
    'device_off': 'Dispositivo Apagado',
    'confirm_power_on': 'Encender equipo',
    'confirm_power_on_desc': 'Control no está activado para este equipo.',

    // Historical Modal
    'date_range': 'Rango de Fechas',
    'data_to_visualize': 'Datos a Visualizar',
    'generate_chart': 'Generar Gráfico',
    'generate_table': 'Generar Tabla',
    'download_pdf': 'Descargar PDF',
    'download_csv': 'Descargar CSV',
    'download_excel': 'Descargar Excel',
    'generate_table_to_load': 'Elija fechas y pulse «Generar Tabla» para cargar la tabla',
    'temperature': 'Temperatura',
    'humidity': 'Humedad',
    'ethylene': 'Etileno',
    'co2': 'CO2',
    'process_summary': 'Resumen del Proceso',
    'viewing_history': 'Visualizando Historial',
    'close': 'Cerrar',

    // Device Card
    'rename_device': 'Renombrar dispositivo',
    'device_name_placeholder': 'Nombre del dispositivo',
    'name_updated': 'Nombre actualizado',
    'error_updating_name': 'Error al actualizar nombre',
    'device_disconnected': 'Dispositivo Desconectado',
    'last_connection': 'Última conexión',
    'last_values_registered_hint': 'Valores mostrados: última telemetría registrada antes de perder el enlace (sin conexión en vivo).',

    'process': 'Proceso',
    'control_module_title': 'Módulo control (panel)',
    'no_control_process_active': 'No hay un proceso de control iniciado desde el panel (Homogenización, Maduración, Ventilación, Enfriamiento).',
    'active_control_process': 'Proceso de control activo',
    'control_process_params': 'Parámetros guardados',
    'hours_progress': 'Avance (tiempo)',
    'control_process_estimated_end': 'Fin estimado',
    'control_process_started': 'Proceso registrado e iniciado',
    'control_process_confirm': 'Confirmar e iniciar',
    'control_process_confirm_title': 'Confirmar inicio de proceso',
    'control_process_time_hint': 'Revise inicio, fin estimado y parámetros.',
    'control_process_replace_title': 'Cambio de proceso',
    'control_process_replace_desc': 'Ya hay un proceso de control activo en este equipo. Si continúa, el anterior se cancelará y se guardará el nuevo.',
    'current': 'Actual',
    'new': 'Nuevo',
    'control_process_cancel_confirm': '¿Cancelar el proceso de control en curso?',
    'control_process_cancelled': 'Proceso cancelado',
    'cancel_process': 'Cancelar proceso',
    'continue': 'Continuar',
    'control_sessions_admin': 'Procesos de control guardados (histórico)',
    'control_sessions_subtitle': 'Listado e histórico de sesiones iniciadas desde el panel de control (Homogenización, Maduración, Ventilación, Enfriamiento). Los administradores ven todas; el resto, solo las suyas.',
    'control_sessions_page_title': 'Control de dispositivos — Procesos confirmados',
    'control_sessions_hint_fleet': 'Desde el panel principal abra un equipo e inicie un proceso; al confirmarlo en el modal, el registro aparece aquí.',
    'control_sessions_load_error': 'No se pudo cargar el listado de procesos.',
    'control_sessions_load_error_hint': 'Compruebe que la API Ripener esté disponible (VITE_RIPENER_API_URL) y que su sesión sea válida.',
    'refresh': 'Actualizar',
    'control_session_edit_title': 'Editar proceso activo',
    'control_session_edit_duration_hint': 'Se recalcula el fin estimado a partir del inicio original y la nueva duración.',
    'control_session_params_invalid_json': 'El campo de parámetros debe ser un objeto JSON válido.',
    'control_session_duration_invalid': 'Indique una duración en horas mayor que cero.',
    'control_session_updated': 'Cambios guardados',
    'control_session_delete': 'Eliminar',
    'control_session_delete_confirm': '¿Eliminar este registro del listado? (No afecta a procesos activos; cancele primero si aplica.)',
    'control_session_deleted': 'Registro eliminado',
    'control_session_delete_active_hint': 'Cancele el proceso activo antes de eliminar el registro.',

    // Bitácora
    'event_log': 'Bitácora',
    'event_log_desc': 'Eventos y muestreos del equipo',
    'log_type': 'Tipo',
    'log_event': 'Evento',
    'log_sampling': 'Muestreo',
    'log_date_time': 'Fecha y hora',
    'log_description': 'Descripción',
    'log_temp': 'T°',
    'log_humidity': 'HR%',
    'log_ethylene': 'Etileno',
    'log_co2': 'CO₂%',
    'log_filter_all': 'Todos',
    'log_filter_events': 'Solo eventos',
    'log_filter_samplings': 'Solo muestreos',

    // Recipes
    'recipe_library': 'Biblioteca de Recetas',
    'recipe_library_desc': 'Protocolos estandarizados para operaciones en Perú.',
    'recipe_standard_badge': 'Estándar',
    'recipe_dup_suffix': '(copia)',
    'recipe_dup_modal_title': 'Duplicar receta',
    'recipe_dup_modal_hint': 'Indica un nombre y revisa el producto y la nota. Las fases se copian tal como están; la podrás ajustar en el editor a continuación.',
    'recipe_dup_continue': 'Continuar al editor',
    'recipe_dup_phases_summary': 'Fases que se copian',
    'recipe_dup_phases_editable_later': 'Se copian con los mismos parámetros. Podrás modificarlas en el siguiente paso.',
    'recipe_name_required': 'Escribe un nombre para la copia',
    'source_recipe': 'Origen',
    'duplicate_recipe': 'Duplicar',
    'recipes_cannot_delete_system': 'Las recetas estándar no se pueden eliminar. Use «Duplicar» para crear una versión personalizada.',
    'recipes_cannot_save_system': 'No se puede guardar sobre una receta estándar. Duplique y edite la copia.',
    'loading_catalog': 'Cargando recetas y productos…',
    'load_error': 'Error al cargar datos.',
    'retry': 'Reintentar',
    'recipes_confirm_delete': '¿Eliminar esta receta?',
    'total_label': 'Total',
    'products_section_title': 'Catálogo de productos',
    'products_section_desc': 'Los nombres aparecen al elegir producto en cada receta.',
    'products_add': 'Agregar producto',
    'products_edit': 'Editar producto',
    'products_delete': 'Eliminar',
    'products_name': 'Nombre',
    'products_empty': 'No hay productos. Agregue al menos uno para asociar recetas.',
    'products_confirm_delete': '¿Eliminar este producto del catálogo?',
    'new_recipe': 'Nueva Receta',
    'edit_recipe': 'Editar Receta',
    'recipe_view_title': 'Detalle de la receta',
    'recipe_view_action': 'Ver detalles',
    'recipe_system_readonly_hint': 'Receta estándar: solo lectura. Usa «Duplicar» para crear una copia editable.',
    'back_to_recipe_list': 'Volver a la lista de recetas',
    'search_recipe_placeholder': 'Buscar receta (ej. Mango, Palta)...',
    'no_description': 'Sin descripción.',
    'total_duration': 'Duración Total',
    'hours': 'horas',
    'minutes': 'minutos',
    'save': 'Guardar',
    
    // Recipe Builder
    'protocol_name': 'Nombre del Protocolo',
    'protocol_placeholder': 'Ej. Mango Kent Exportación Europa',
    'product_label': 'Producto',
    'product_search_placeholder': 'Buscar o escribir y elegir producto…',
    'no_product_matches': 'Ninguna coincidencia. Escribe para filtrar o crea un producto.',
    'product_combobox_create': 'Crear producto',
    'product_create_in_recipe_hint': 'Se guarda en el catálogo y queda elegido para esta receta.',
    'open_product_list': 'Abrir lista de productos',
    'description_notes': 'Descripción / Notas',
    'description_placeholder': 'Detalles adicionales...',
    'logical_process_sequence': 'Secuencia Lógica de Proceso',
    
    // Phases
    'phase_homogenization': '1. Homogeneización',
    'phase_homogenization_desc': 'Uniformizar temperatura de la pulpa.',
    'phase_ripening': '2. Maduración / Disparo',
    'phase_ripening_desc': 'Inyección de etileno y control de gases.',
    'phase_venting': '3. Ventilación',
    'phase_venting_desc': 'Extracción de CO2 y aire fresco.',
    'phase_cooling': '4. Enfriamiento / Cooling',
    'phase_cooling_desc': 'Reducción temperatura a nivel de despacho.',
    
    // Phase Status/Controls
    'set_temperature': 'Set Temperatura',
    'set_time': 'Tiempo',
    'set_ethylene': 'Set Etileno',
    'set_co2': 'Set CO2',
    'set_humidity': 'Set Humedad',
    'target_product_temp': 'Temp. Objetivo Producto',
    'pulp_temp_control_note': '*Se controla por temp de pulpa',
    
    // Units/Labels
    'unit_hours': 'Horas',
    'unit_minutes': 'Minutos',
    'unit_ppm': 'ppm',
    'short_homog': 'Homog.',
    'short_ripening': 'Maduración',
    'short_venting': 'Vent.',
    'short_cooling': 'Frío',

    // User Manual
    'user_manual': 'Manual de Usuario',
    'user_manual_desc': 'Guía completa del sistema con capturas y explicaciones.',
    'table_of_contents': 'Tabla de Contenidos',
    'manual_intro': 'Introducción al Sistema',
    'manual_intro_desc': 'Sistema integral de gestión y monitoreo en tiempo real para contenedores refrigerados REEFER de 40 pies, diseñado para el control automatizado de procesos de maduración de frutas.',
    
    // Manual Sections
    'section_login': '1. Inicio de Sesión',
    'section_login_desc': 'Acceso al sistema mediante credenciales de usuario.',
    'section_dashboard': '2. Panel de Control',
    'section_dashboard_desc': 'Vista general de la flota y métricas operacionales.',
    'section_device_control': '3. Control de Dispositivos',
    'section_device_control_desc': 'Gestión individual de equipos en modo manual.',
    'section_device_detail': '4. Detalle de Dispositivo',
    'section_device_detail_desc': 'Información completa y telemetría en tiempo real.',
    'section_monitoring': '5. Monitoreo y Análisis',
    'section_monitoring_desc': 'Gráficas históricas y métricas de rendimiento.',
    'section_processes': '6. Seguimiento de Procesos (PLUS)',
    'section_processes_desc': 'Gestión de lotes y seguimiento de maduración.',
    'section_recipes': '7. Biblioteca de Recetas (PLUS)',
    'section_recipes_desc': 'Protocolos estandarizados y recetas personalizadas.',
    'section_recipe_builder': '8. Constructor de Recetas',
    'section_recipe_builder_desc': 'Creación de protocolos paso a paso.',
    'section_users': '9. Gestión de Usuarios (PLUS)',
    'section_users_desc': 'Administración de cuentas y permisos.',
    'section_profile': '10. Perfil de Usuario',
    'section_profile_desc': 'Configuración personal y preferencias.',
    
    // Login Section Details
    'login_step1': 'Ingrese su correo electrónico corporativo.',
    'login_step2': 'Ingrese su contraseña asignada.',
    'login_step3': 'Presione \"Iniciar Sesión\" para acceder al sistema.',
    'login_step4': 'El sistema validará las credenciales y lo redirigirá automáticamente al Dashboard.',
    'login_note': 'Si olvida su contraseña, contacte al administrador del sistema para restablecerla.',
    
    // Dashboard Section Details
    'dashboard_step1': 'Visualice las 4 métricas generales en la parte superior: Unidades Activas (3/5), Alarmas Activas (2), Procesos Completados (47 esta semana) y Consumo Total (2,847 kWh).',
    'dashboard_step2': 'Cada tarjeta de dispositivo muestra el estado con código de colores: Verde (Activo), Naranja (Advertencia), Azul (Homogenización), Gris (Offline).',
    'dashboard_step3': 'Revise los valores en tiempo real de cada REEFER: Temperatura, Humedad, Etileno (C₂H₄) y CO₂.',
    'dashboard_step4': 'Observe la receta activa y fase actual del proceso en la parte inferior de cada tarjeta.',
    'dashboard_step5': 'Use la barra de búsqueda superior para filtrar dispositivos por ID o estado.',
    'dashboard_step6': 'Haga clic en cualquier tarjeta para acceder al panel de control detallado del dispositivo.',
    'dashboard_note': 'Los colores de borde indican urgencia: Verde (Normal), Naranja (Requiere Atención), Rojo (Alarma Crítica). El Dashboard se actualiza automáticamente cada 30 segundos.',
    
    // Device Control Details
    'control_step1': 'Seleccione un dispositivo haciendo clic en su tarjeta desde el Dashboard.',
    'control_step2': 'Verifique el estado de encendido en la parte superior (Power ON/OFF con indicador verde).',
    'control_step3': 'Revise los valores actuales en el panel azul: Temperatura actual, Humedad actual, Etileno actual y CO₂ actual.',
    'control_step4': 'Active el modo de control manual desactivando el control automático.',
    'control_step5': 'Ajuste los parámetros objetivo respetando los rangos permitidos: Temperatura (5°C - 25°C), Humedad (70% - 95%), Etileno (0 - 200 ppm).',
    'control_step6': 'Observe las indicaciones de rango debajo de cada campo de entrada.',
    'control_step7': 'Presione \"Aplicar Cambios\" y confirme en el diálogo de confirmación para enviar los nuevos setpoints al dispositivo.',
    'control_note': 'Los cambios solo se pueden aplicar si el dispositivo está encendido y en modo manual. El sistema confirmará la aplicación exitosa de los cambios con una notificación.',
    
    // Device Detail Details
    'detail_step1': 'Acceda haciendo clic en cualquier tarjeta de dispositivo del Dashboard para ver su información completa.',
    'detail_step2': 'En la vista superior, observe las 4 métricas principales con tendencias: Temperatura (↑+0.3°C en 1h), Humedad (↓-2% en 1h), Etileno (Estable), CO₂ (↑+0.2% en 1h).',
    'detail_step3': 'Revise el panel azul de progreso del proceso activo: nombre de receta (ej: Mango Kent Exportación), fase actual (Maduración - Hora 32 de 48), y porcentaje de progreso (67%).',
    'detail_step4': 'Consulte la tabla de \"Últimas 12 Horas\" que muestra registros cada 30 minutos con Temperatura, Humedad y CO₂.',
    'detail_step5': 'Use el botón \"Datos Históricos\" para abrir el modal de calendario y consultar rangos de fechas específicos.',
    'detail_step6': 'Navegue entre las pestañas \"Operación\" (control manual) y \"Análisis\" (gráficas históricas) según necesidad.',
    'detail_note': 'Los datos históricos se almacenan por 90 días. Las flechas de tendencia (↑↓) indican cambios en la última hora. La tabla muestra 8 de 24 registros disponibles.',
    
    // Monitoring Details
    'monitoring_step1': 'Navegue a \"Monitoreo y Análisis\" desde el menú lateral izquierdo.',
    'monitoring_step2': 'Seleccione un dispositivo del selector para ver sus métricas detalladas en gráficas.',
    'monitoring_step3': 'Configure el rango de fechas usando el calendario: puede consultar desde 1 hora hasta 90 días atrás.',
    'monitoring_step4': 'Active o desactive las métricas en la leyenda de la gráfica: Temperatura (azul), Humedad (verde), CO₂ (naranja).',
    'monitoring_step5': 'Use los botones de zoom y pan para explorar períodos específicos con detalle.',
    'monitoring_note': 'Las gráficas muestran las últimas 12 horas por defecto. Puede exportar los datos en formato CSV para análisis offline o generar reportes en PDF.',
    
    // Processes Details
    'processes_step1': 'Acceda a \"Seguimiento (Plus)\" desde el menú lateral para ver todos los lotes de maduración.',
    'processes_step2': 'Visualice los 4 estados de procesos: En Proceso (verde), Homogenización (azul), Ventilación (naranja), Completado (gris).',
    'processes_step3': 'Para cada proceso, observe: Lote# (ej: MAG-2024-001), Cliente (Exportadora San Miguel SAC), Producto (Mango Kent), Dispositivo (REEFER-001).',
    'processes_step4': 'Revise el progreso de las 4 fases en la barra inferior: Homogenización (24h ✓), Maduración (32/48h activo), Ventilación (0/8h), Enfriamiento (0/12h).',
    'processes_step5': 'Haga clic en \"Nuevo Proceso\" para iniciar un nuevo lote de maduración.',
    'processes_step6': 'Complete el formulario: datos del cliente, número de lote, producto, peso, seleccione receta de la biblioteca.',
    'processes_step7': 'Asigne un dispositivo disponible y confirme para que el sistema inicie automáticamente el proceso siguiendo la receta.',
    'processes_note': 'El sistema rastreará automáticamente cada fase y enviará notificaciones al completar cada etapa. Los procesos completados se archivan y pueden consultarse en el historial.',
    
    // Recipes Details
    'recipes_step1': 'Navegue a \"Recetas (Plus)\" desde el menú para acceder a la biblioteca de protocolos de maduración.',
    'recipes_step2': 'Tres recetas estándar (no eliminables): Aguacate, Mango y Banano, con parámetros típicos de cámara (temperatura, humedad, etileno, CO₂). Duplique para personalizar.',
    'recipes_step3': 'Cada tarjeta muestra: producto, duración total, y configuración de las 4 fases con tiempos específicos.',
    'recipes_step4': 'Observe los detalles de cada fase: 1. Homogenización (temp, humedad, tiempo), 2. Maduración (temp, humedad, etileno, tiempo), 3. Ventilación (temp, humedad, tiempo), 4. Enfriamiento (temp, humedad, tiempo).',
    'recipes_step5': 'Haga clic en \"Nueva Receta\" para crear un protocolo personalizado siguiendo la secuencia obligatoria de fases.',
    'recipes_note': 'Las recetas estándar se actualizan con el catálogo; use «Duplicar» para crear copias editables. No se pueden eliminar las estándar.',
    
    // Recipe Builder Details
    'builder_step1': 'Desde \"Recetas\", presione \"Nueva Receta\" para abrir el constructor de protocolos.',
    'builder_step2': 'Ingrese un nombre descriptivo (ej: \"Mango Kent Exportación Premium\") y seleccione el producto.',
    'builder_step3': 'Configure FASE 1 - HOMOGENIZACIÓN: Temperatura (°C), Humedad (%), Tiempo (horas). Esta fase iguala la temperatura de toda la fruta sin aplicar etileno.',
    'builder_step4': 'Configure FASE 2 - MADURACIÓN: Temperatura (°C), Humedad (%), Etileno (ppm), Tiempo (horas). Esta es la fase crítica donde se acelera la maduración.',
    'builder_step5': 'Configure FASE 3 - VENTILACIÓN: Temperatura (°C), Humedad (%), Tiempo (horas). Elimina gases residuales (C₂H₄ y CO₂) con ventilación al 100%.',
    'builder_step6': 'Configure FASE 4 - ENFRIAMIENTO: Temperatura (°C), Humedad (%), Tiempo (horas). Reduce temperatura gradualmente para detener maduración.',
    'builder_step7': 'Respete los rangos permitidos: Temperatura (5-25°C), Humedad (70-95%), Etileno (0-200ppm), Tiempo (1-72h por fase).',
    'builder_step8': 'Observe la duración total calculada automáticamente en el panel inferior (suma de las 4 fases).',
    'builder_step9': 'Revise las notas informativas de cada fase (ℹ️) que explican el propósito y consideraciones especiales.',
    'builder_step10': 'Presione \"Guardar\" para agregar la receta a la biblioteca y usarla en nuevos procesos de maduración.',
    'builder_note': 'La secuencia de fases es inviolable (Homog→Maduración→Ventilación→Enfriamiento) y sigue la lógica técnica de maduración controlada. Evite tiempos muy cortos (<6h) o temperaturas extremas.',
  },
  en: {
    // Navigation
    'dashboard': 'Dashboard',
    'control': 'Device Control',
    'monitoring': 'Monitoring & Analysis',
    'processes': 'Tracking (Plus)',
    'control_module_menu': 'Control processes (panel)',
    'recipes': 'Recipes (Plus)',
    'users': 'Users (Plus)',
    'settings': 'Settings',
    'help': 'User Manual',
    'logout': 'Log Out',
    'profile': 'My Profile',
    'operator': 'Operator',
    'search_placeholder': 'Search device...',
    'search_process_placeholder': 'Search by client, batch or product...',

    // Login
    'welcome_back': 'Welcome back',
    'enter_credentials': 'Enter your credentials to access the control panel',
    'password': 'Password',
    'login_button': 'Log In',
    'login_subtitle': 'Real-time management and monitoring system for refrigerated containers.',
    'configuring': 'Configuring...',
    'init_admin': 'Initialize Admin Account (Dev)',
    'session_success': 'Session started successfully',
    'admin_ready': 'Admin account ready',
    'login_error': 'Error logging in',
    'email_label': 'Email Address',

    // Dashboard
    'active_units': 'Active Units',
    'active_alarms': 'Active Alarms',
    'completed_processes': 'Completed Processes',
    'processes_in_progress': 'Processes in progress',
    'alarms_numero_sum_hint': 'Σ alarm number (API)',
    'processes_in_progress_hint': 'Excluding Manual',
    'total_consumption': 'Total Consumption',
    'fleet_status': 'Fleet Status',
    'executive_summary': 'Executive summary',
    'download_executive_summary': 'Download executive summary (PDF)',
    'of_total': 'Of {{total}} total',
    'require_attention': 'Require attention',
    'this_week': 'This week',
    'historical_accumulated': 'Historical accumulated',
    'units_online': 'Units online',
    'device': 'Unit',
    'last_data': 'Last data',
    'online': 'Online',
    'wait': 'Wait',
    'offline': 'Offline',
    'connection': 'Connection',
    'equipment': 'Equipment',
    'error_loading_devices': 'Error loading devices',

    // Device Detail
    'device_not_found': 'Device not found',
    'operation': 'Operation',
    'analysis': 'Analysis',
    'current_process_status': 'Current Process Status',
    'status_current_title': 'Current status',
    'status_show_more': 'Show more',
    'status_show_less': 'Show less',
    'status_temp_supply': 'Supply T°',
    'status_return': 'Return T°',
    'status_ethylene': 'Ethylene level',
    'status_alarms': 'Messages',
    'status_ventilation': 'Ventilation',
    'status_humidity': 'Humidity',
    'status_co2': 'CO₂ level',
    'status_capacity': 'Power (%)',
    'status_evap': 'Evap. T°',
    'status_cond': 'Cond. T°',
    'status_compressor': 'Compressor T°',
    'status_ambient': 'Ambient T°',
    'status_cargo_n': 'Sensor {{n}} T°',
    'status_line_voltage': 'Line voltage',
    'status_line_frequency': 'Line frequency',
    'status_phase_n': 'Phase {{n}}',
    'status_sp_co2': 'CO₂ SP',
    'status_kwh': 'Electrical use',
    'status_gas_exchange': 'Air exchange',
    'status_sp_ethylene': 'Ethylene SP',
    'vent_na': 'N/A',
    'cfm_unit': 'CFM',
    'sp_ethyleno_unit': 'ppm',
    'gas_ex_off': 'Off',
    'gas_ex_manual': 'Manual',
    'gas_ex_auto': 'Auto',
    'temp_unit_hint': 'Temperature unit (°C/°F):',
    'timezone_display_label': 'Time (time zone)',
    'timezone_data_hint': 'Telemetry is shown in the selected time zone. Default GMT-5. Switch to GMT-4, GMT-6, Mexico, etc. as needed.',
    'tz_reference_gmt5': 'GMT-5 (default reference)',
    'tz_gmt4': 'GMT-4',
    'tz_gmt5': 'GMT-5',
    'tz_gmt6': 'GMT-6',
    'tz_gmt7': 'GMT-7',
    'tz_gmt8': 'GMT-8',
    'tz_gmt3': 'GMT-3',
    'tz_mexico_city': 'Mexico (official)',
    'tz_bogota': 'Colombia',
    'tz_lima': 'Peru',
    'tz_utc': 'UTC (reference)',
    'operational_data': 'Operational Data',
    'no_active_process': 'No active process',
    'power_consumption': 'Power Consumption',
    'energy_consumption_period': 'Energy consumption (period)',
    'total_accumulated': 'Total Accumulated',
    'defrost_interval': 'Defrost Interval',
    'evaporation_coil': 'Evaporation Coil',
    'recipe': 'Recipe',
    'phase': 'Phase',
    'start': 'Start',
    'end': 'End',
    'estimated_end': 'Estimated End',
    'back': 'Back',
    'historical_data': 'Historical Data',
    'historical_data_table': 'Data in table',
    'last_12_hours': 'Last 12 Hours',
    'last_12h_no_data_title': 'No data in the last 12 hours',
    'last_12h_no_data_madurador': 'No return-air temp, humidity, ethylene (campo_1), or CO₂ (co2_reading) in the window. If `cantidad_datos` is 0 at the source, there is no history yet.',
    'preset_last12': 'Last 12 h',
    'preset_basic': 'Basic (Temp, RH, Ethylene, CO₂)',
    'preset_temperatures': 'Temperatures only',
    'preset_gases': 'Gases & humidity',
    'preset_full': 'Full',
    'columns_to_show': 'Columns to show',
    'search_by_date': 'Search by date',

    // Control Panel
    'manual_mode': 'Manual',
    'homogenization': 'Homogenization',
    'ripening': 'Ripening',
    'ventilation': 'Ventilation',
    'cooling': 'Cooling',
    'process_integral': 'Integral / automatic process',
    'process_manual_name': 'Manual',
    'process_unknown': 'Process',
    'fleet_process_panel': 'Process (control panel)',
    'device_status': 'Device Status',
    'equipo_estado_actual': 'Current equipment state',
    'controls_available_when_on': 'Temperature, humidity and gas controls are available when the equipment is on.',
    'climatization': 'Climatization',
    'target_temperature': 'Target Temperature',
    'relative_humidity': 'Relative Humidity',
    'gases_ventilation': 'Gases & Ventilation',
    'ethylene_injection': 'Ethylene Injection',
    'ventilation_speed': 'Ventilation Speed',
    'apply_changes': 'Apply Changes',
    'confirm_changes': 'Confirm Changes',
    'applying': 'Applying...',
    'confirm_changes_desc': 'The following changes will be applied to the device:',
    'environmental_conditions': 'Environmental Conditions',
    'target_co2': 'Target CO2',
    'duration': 'Duration',
    'preview': 'Preview',
    'start_process': 'Start Process',
    'starting': 'Starting...',
    'cancel': 'Cancel',
    'final_temperature': 'Final Temperature',
    'estimated_duration': 'Estimated Duration',
    'co2_limit': 'CO2 Limit',
    'process_time': 'Process Time',
    'max_duration': 'Max Duration',
    'cooling_ramp': 'Cooling Ramp',

    // Process List
    'process_tracking': 'Process Tracking',
    'process_tracking_desc': 'Manage active batches, history, and new services.',
    'new_process': 'New Process',
    'filters': 'Filters',
    'in_process': 'IN PROCESS',
    'attention': 'ATTENTION',
    'current_phase': 'Current Phase',
    'estimated_progress': 'Estimated Progress',
    'view_details': 'View Details',
    'start_new_process': 'Start New Process',
    'start_new_process_desc': 'Configure a new batch and assign a maturation recipe.',
    'process_data_mgmt': 'Data management',
    'process_data_mgmt_desc': 'All saved processes: open or delete.',
    'no_saved_processes': 'No saved processes yet.',
    'confirm_delete_process': 'Delete this process? This cannot be undone.',
    'process_name_col': 'Name',
    'client': 'Client',
    'created': 'Created',
    'action_delete': 'Delete',
    'loading': 'Loading…',
    'saving_process': 'Saving…',
    'load_processes_error': 'Could not load processes.',
    'seguimiento': 'Tracking',
    'field_process_name': 'Process',
    'device_active_check_loading': 'Checking if this unit already has a process in progress…',
    'device_active_process_title': 'This device already has an active process',
    'device_active_process_body':
      'Only one process at a time can be active on this device. You can open the current process from the list, but no new samplings are allowed on it if it is cancelled. Continuing will set the in‑progress process to CANCELLED (kept for traceability) and the new one will be active.',
    'device_active_ack_replace':
      'I understand: the current process for this device will be cancelled and the new one will replace it. No further samplings can be added to the cancelled process.',
    'status_ripening_cancelled': 'CANCELLED',
    'process_cancelled_info':
      'This process is cancelled. Records and the log remain for traceability. New samplings are not allowed.',
    'sampling_forbidden_cancelled': 'Cannot add samplings to a cancelled process.',
    'process_not_active_generic': 'This process is not active; new samplings cannot be recorded.',

    // Tracking / final report
    'report_title_interim': 'Progress report',
    'report_title_final': 'Final ripening report',
    'report_subtitle_active': 'Sampling summary and parameter evolution to date.',
    'report_subtitle_closed': 'Process completed: full sampling history and trends.',
    'report_subtitle_cancelled':
      'Process cancelled: traceability of registered samplings and parameters is preserved.',
    'report_final_banner_title': 'Final report available',
    'report_final_banner_desc':
      'View the report with all samplings and Brix, firmness, and color evolution. Print or save as PDF from the browser.',
    'report_open_interim': 'Progress report',
    'report_open_final': 'View final report',
    'report_section_process': 'Process details',
    'report_section_samplings': 'Registered samplings',
    'report_section_evolution': 'Parameter evolution',
    'report_field_id': 'ID',
    'report_recipe': 'Recipe',
    'report_targets': 'Targets (recipe)',
    'report_started': 'Started',
    'report_estimated_end': 'Estimated end',
    'report_col_date': 'Date & time',
    'report_col_type': 'Type / title',
    'report_col_person': 'Responsible',
    'report_col_params': 'Measured parameters',
    'report_col_notes': 'Notes',
    'report_no_samplings': 'No samplings in the log yet.',
    'report_evolution_note': 'Numeric values by sampling index (chronological order). Lines skip missing points.',
    'report_param_brix': 'Brix (°)',
    'report_param_firmness': 'Firmness',
    'report_param_color': 'Color',
    'report_param_firmness_short': 'Firmness',
    'report_param_color_short': 'Color',
    'report_x_axis': 'Sampling #',
    'report_no_numeric_params':
      'No recognizable numeric Brix / firmness / color values to plot. Data remains in the table.',
    'report_generated_at': 'Generated:',
    'report_close': 'Close',
    'report_print': 'Print / PDF',

    // Create Process Form
    'new_maturation_process': 'New Maturation Process',
    'new_process_desc': 'Enter batch data and configure initial parameters.',
    'client_info': 'Client Information',
    'client_type': 'Client Type',
    'client_name': 'Client Name / Company',
    'batch_details': 'Batch Details',
    'product': 'Product',
    'quantity_kg': 'Quantity (kg)',
    'control_device': 'Control Device',
    'recipe_planning': 'Recipe & Planning',
    'select_recipe_library': 'Select Recipe from Library',
    'create_edit_custom': 'Create/Edit Custom',
    'process_display_name': 'Process name (optional)',
    'process_name_auto_hint': 'If left empty, it will be: Product + Client/Company + Control device + Date (day/month/year).',
    'client_type_external': 'External service',
    'client_type_internal': 'In-house / internal',
    'lot_origin': 'Origin / lot',
    'lot_origin_ph': 'Farm, region, lot note…',
    'batch_volume_m3': 'Batch volume (m³, optional)',
    'no_device': 'no device',
    'loading_devices': 'Loading devices…',
    'control_device_list_hint': 'Same fleet as the control panel. Off units are included; they are expected to start when the process begins.',
    'select_device_placeholder': '— Select control device —',
    'estado': 'State',
    'estado_on': 'On',
    'estado_off': 'Off',
    'humidity_set_point_label': 'Humidity setpoint (RH)',
    'set_point_co2_label': 'CO₂ setpoint',
    'set_temp_label': 'Temperature setpoint',
    'control_device_off_note': 'If the unit is off, it is assumed it will be turned on when the process starts.',
    'select_product_first_for_recipes': 'Select a product from the catalog first; recipes are filtered for that product (as in the recipe library).',
    'no_recipes_for_product': 'No recipes in the catalog for this product. You can create a custom recipe.',
    'select_recipe_option': '— Select recipe —',
    'custom_recipe_current': 'Current custom recipe',
    'process_start_time': 'Process start date/time',
    'start_now_button': 'Right now',
    'start_schedule_label': 'Schedule start',
    'target_objectives_title': 'Target parameters',
    'no_objectives_check': "Don't set targets",
    'objectives_optional': 'Optional. Enter quality targets if needed.',
    'new_param_name_placeholder': 'Parameter name',
    'unit_custom': 'custom',
    'initial_sampling_block_title': 'Initial sampling (reception)',
    'initial_sampling_block_desc': 'Same fields as «Register sampling» — only Initial / reception. Parameters and photos are optional.',
    'sampling_type_initial_only': 'Initial / reception',
    'sampling_notes': 'Sampling notes',
    'sampling_notes_ph': 'Fruit condition, issues…',
    'sampling_observations_required': 'Initial sampling notes are required (process tracking record).',
    'sampling_photo_evidence': 'Photo evidence',
    'sampling_photos_optional': 'One or more images, optional. Local preview until the process is confirmed.',
    'sampling_register': 'Log sampling',
    'sampling_save': 'Save sampling',
    'sampling_person_field': 'Person performing sampling',
    'sampling_person_ph': 'Full name / who takes the sample',
    'sampling_person_field_hint': 'Defaults to your name. The session user who submits is always stored in the system.',
    'sampling_executed_by': 'Sampling by',
    'registered_in_system': 'Recorded in the system (session user)',
    'sampling_photos_multi_hint': 'Multiple images: select several at once or add in multiple steps. Optional. JPG, PNG.',
    'field_supervisor': 'Process supervisor',
    'process_supervisor_title': 'Process supervisor (required)',
    'process_supervisor_desc': 'Accountable for the batch. Prefilled with your account; you may edit it.',
    'supervisor_name': 'Supervisor name',
    'supervisor_email_optional': 'Supervisor email (optional)',
    'supervisor_required': 'Please enter the process supervisor name.',
    'sampling_person_required': 'Please enter who performs the initial sampling.',
    'initial_sampling_person': 'Person performing initial sampling',
    'initial_sampling_person_ph': 'Who records the reception sampling',
    'initial_sampling_person_hint': 'Defaults to your name. The system stores who submitted the record (signed-in user).',
    'sampling_remove_photo': 'Remove photo',
    'sampling_result_tracking_note': 'This sampling is stored as part of process tracking. Only the notes field is required.',
    'sampling_params_all_optional': 'Measured parameters are optional.',
    'back_to_process_list': 'Back to process list',
    'process_recipe_total_hours': 'Total duration (sum of recipe phases): {{hours}} h',
    'process_estimated_end': 'Approximate end of process: {{date}}',

    // Users
    'user_management': 'User Management',
    'new_user': 'New User',
    'system_users': 'System Users',
    'user': 'User',
    'email': 'Email',
    'role': 'Role',
    'status': 'Status',
    'actions': 'Actions',
    'edit': 'Edit',
    'edit_user': 'Edit user',
    'active': 'Active',
    'inactive': 'Inactive',
    'full_name': 'Full name',
    'delete': 'Delete',
    'delete_user': 'Delete user',
    'confirm_delete_user': 'Deactivate {{name}}? They will be removed from the list (logical delete).',
    'user_created': 'User created',
    'user_updated': 'User updated',
    'user_deleted': 'User deactivated',
    'error_users': 'Failed to load users',
    'no_users_yet': 'No users yet. Create one with «New User».',
    'duplicate_email': 'An active user with this email already exists',
    'role_admin': 'Administrator',
    'role_operator': 'Operator',
    'role_viewer': 'Viewer',
    'role_superadmin': 'Super administrator',
    'company_field': 'Company',
    'company_placeholder': 'Empty = “no company”',
    'identificador_field': 'Company ID (Madurador API)',
    'identificador_field_short': 'Co. ID',
    'identificador_placeholder': 'e.g. 1001',
    'identificador_hint': 'Optional. When set, the app loads devices from the Madurador API for that identifier.',
    'madurador_reference_title': 'Equipment reference (Madurador)',
    'madurador_detail_estado': 'Equipment state',
    'madurador_detail_supply': 'Supply temp.',
    'madurador_detail_return': 'Return air',
    'madurador_detail_evap': 'Evaporator',
    'madurador_detail_cond': 'Condenser',
    'madurador_detail_compressor': 'Compressor',
    'madurador_detail_avl': 'Ventilation (avl / CFM)',
    'madurador_detail_voltage': 'Line voltage',
    'madurador_detail_set_co2': 'CO₂ setpoint',
    'madurador_detail_set_hum': 'Humidity setpoint',
    'madurador_detail_capacity': 'Compressor load %',
    'madurador_last_on': 'Last power-on',
    'madurador_last_sample': 'Last telemetry sample',
    'madurador_until': 'Data as of',
    'madurador_process_start': 'Process start',
    'madurador_fecha_procesada': 'Last processed (server)',
    'photo_label': 'Profile photo',
    'photo_choose_file': 'Choose image',
    'photo_change_file': 'Change image',
    'photo_remove_selection': 'Remove selection',
    'photo_preview_hint': 'Preview. The image uploads when you save.',
    'photo_current_hint': 'Current photo on server.',
    'password_new_user': 'Password',
    'password_required_new': 'Set a password for the new user',
    'password_change_hint': 'New password',
    'password_optional_placeholder': 'Leave blank to keep current',

    // Status
    'status_active': 'Active',
    'status_warning': 'Warning',
    'status_alarm': 'Alarm',
    'status_offline': 'Offline',
    'status_standby': 'Standby',
    'status_powered_on': 'On',
    'status_powered_off': 'Off',
    'completed': 'Completed',
    'turn_on': 'Turn On',
    'turn_off': 'Turn Off',
    'device_on': 'Device On',
    'device_off': 'Device Off',
    'confirm_power_on': 'Turn on device',
    'confirm_power_on_desc': 'Control is not enabled for this device.',

    // Historical Modal
    'date_range': 'Date Range',
    'data_to_visualize': 'Data to Visualize',
    'generate_chart': 'Generate Chart',
    'generate_table': 'Generate Table',
    'download_pdf': 'Download PDF',
    'download_csv': 'Download CSV',
    'download_excel': 'Download Excel',
    'generate_table_to_load': 'Select dates and click «Generate Table» to load the table',
    'temperature': 'Temperature',
    'humidity': 'Humidity',
    'ethylene': 'Ethylene',
    'co2': 'CO2',
    'process_summary': 'Process Summary',
    'viewing_history': 'Viewing History',
    'close': 'Close',

    // Device Card
    'rename_device': 'Rename device',
    'device_name_placeholder': 'Device name',
    'name_updated': 'Name updated',
    'error_updating_name': 'Error updating name',
    'device_disconnected': 'Device Disconnected',
    'last_connection': 'Last connection',
    'last_values_registered_hint': 'Values shown: last telemetry before the link was lost (no live connection).',

    'process': 'Process',
    'control_module_title': 'Control module (panel)',
    'no_control_process_active': 'No control process started from the panel (Homogenization, Ripening, Ventilation, Cooling).',
    'active_control_process': 'Active control process',
    'control_process_params': 'Saved parameters',
    'hours_progress': 'Progress (time)',
    'control_process_estimated_end': 'Estimated end',
    'control_process_started': 'Process registered and started',
    'control_process_confirm': 'Confirm and start',
    'control_process_confirm_title': 'Confirm process start',
    'control_process_time_hint': 'Check start, estimated end, and parameters.',
    'control_process_replace_title': 'Change process',
    'control_process_replace_desc': 'A control process is already active. Continuing will cancel it and save the new one.',
    'current': 'Current',
    'new': 'New',
    'control_process_cancel_confirm': 'Cancel the current control process?',
    'control_process_cancelled': 'Process cancelled',
    'cancel_process': 'Cancel process',
    'continue': 'Continue',
    'control_sessions_admin': 'Saved control processes (history)',
    'control_sessions_subtitle': 'List and history of sessions started from the control panel. Admins see all; others only their own.',
    'control_sessions_page_title': 'Device control — Confirmed processes',
    'control_sessions_hint_fleet': 'Open a unit from the main dashboard and start a process; after you confirm it in the modal, it appears here.',
    'control_sessions_load_error': 'Could not load the process list.',
    'control_sessions_load_error_hint': 'Check that the Ripener API is reachable (VITE_RIPENER_API_URL) and your session is valid.',
    'refresh': 'Refresh',
    'control_session_edit_title': 'Edit active process',
    'control_session_edit_duration_hint': 'Estimated end is recalculated from the original start time and the new duration.',
    'control_session_params_invalid_json': 'Parameters must be valid JSON object.',
    'control_session_duration_invalid': 'Enter a duration in hours greater than zero.',
    'control_session_updated': 'Changes saved',
    'control_session_delete': 'Delete',
    'control_session_delete_confirm': 'Delete this record from the list? (Active processes must be cancelled first.)',
    'control_session_deleted': 'Record removed',
    'control_session_delete_active_hint': 'Cancel the active process before deleting the record.',

    // Event log
    'event_log': 'Event Log',
    'event_log_desc': 'Events and samplings for this unit',
    'log_type': 'Type',
    'log_event': 'Event',
    'log_sampling': 'Sampling',
    'log_date_time': 'Date & time',
    'log_description': 'Description',
    'log_temp': 'Temp',
    'log_humidity': 'RH%',
    'log_ethylene': 'Ethylene',
    'log_co2': 'CO₂%',
    'log_filter_all': 'All',
    'log_filter_events': 'Events only',
    'log_filter_samplings': 'Samplings only',

    // Recipes
    'recipe_library': 'Recipe Library',
    'recipe_library_desc': 'Standardized protocols for operations.',
    'recipe_standard_badge': 'Standard',
    'recipe_dup_suffix': '(copy)',
    'recipe_dup_modal_title': 'Duplicate recipe',
    'recipe_dup_modal_hint': 'Set a name and review the product and notes. Phases are copied as-is; you can adjust them in the editor next.',
    'recipe_dup_continue': 'Continue to editor',
    'recipe_dup_phases_summary': 'Phases to copy',
    'recipe_dup_phases_editable_later': 'They copy with the same parameters. You can change them in the next step.',
    'recipe_name_required': 'Enter a name for the copy',
    'source_recipe': 'From',
    'duplicate_recipe': 'Duplicate',
    'recipes_cannot_delete_system': 'Standard recipes cannot be deleted. Use “Duplicate” to create an editable copy.',
    'recipes_cannot_save_system': 'You cannot save over a standard recipe. Duplicate it first, then edit the copy.',
    'loading_catalog': 'Loading recipes and products…',
    'load_error': 'Failed to load data.',
    'retry': 'Retry',
    'recipes_confirm_delete': 'Delete this recipe?',
    'total_label': 'Total',
    'products_section_title': 'Product catalog',
    'products_section_desc': 'These names appear when you choose a product for each recipe.',
    'products_add': 'Add product',
    'products_edit': 'Edit product',
    'products_delete': 'Delete',
    'products_name': 'Name',
    'products_empty': 'No products yet. Add at least one to assign recipes.',
    'products_confirm_delete': 'Remove this product from the catalog?',
    'new_recipe': 'New Recipe',
    'edit_recipe': 'Edit Recipe',
    'recipe_view_title': 'Recipe details',
    'recipe_view_action': 'View details',
    'recipe_system_readonly_hint': 'Standard recipe: read-only. Use «Duplicate» to create an editable copy.',
    'back_to_recipe_list': 'Back to recipe list',
    'search_recipe_placeholder': 'Search recipe (e.g., Mango, Avocado)...',
    'no_description': 'No description.',
    'total_duration': 'Total Duration',
    'hours': 'hours',
    'minutes': 'minutes',
    'save': 'Save',
    
    // Recipe Builder
    'protocol_name': 'Protocol Name',
    'protocol_placeholder': 'E.g., Mango Kent Export Europe',
    'product_label': 'Product',
    'product_search_placeholder': 'Search or type to select a product…',
    'no_product_matches': 'No matches. Type to filter or create a product.',
    'product_combobox_create': 'Create product',
    'product_create_in_recipe_hint': 'It will be saved to the catalog and selected for this recipe.',
    'open_product_list': 'Open product list',
    'description_notes': 'Description / Notes',
    'description_placeholder': 'Additional details...',
    'logical_process_sequence': 'Logical Process Sequence',
    
    // Phases
    'phase_homogenization': '1. Homogenization',
    'phase_homogenization_desc': 'Uniformize pulp temperature.',
    'phase_ripening': '2. Ripening / Trigger',
    'phase_ripening_desc': 'Ethylene injection and gas control.',
    'phase_venting': '3. Venting',
    'phase_venting_desc': 'CO2 extraction and fresh air.',
    'phase_cooling': '4. Cooling',
    'phase_cooling_desc': 'Reduce temperature to dispatch level.',
    
    // Phase Status/Controls
    'set_temperature': 'Set Temperature',
    'set_time': 'Time',
    'set_ethylene': 'Set Ethylene',
    'set_co2': 'Set CO2',
    'set_humidity': 'Set Humidity',
    'target_product_temp': 'Target Product Temp',
    'pulp_temp_control_note': '*Controlled by pulp temp',
    
    // Units/Labels
    'unit_hours': 'Hours',
    'unit_minutes': 'Minutes',
    'unit_ppm': 'ppm',
    'short_homog': 'Homog.',
    'short_ripening': 'Ripening',
    'short_venting': 'Vent.',
    'short_cooling': 'Cooling',

    // User Manual
    'user_manual': 'User Manual',
    'user_manual_desc': 'Complete system guide with screenshots and explanations.',
    'table_of_contents': 'Table of Contents',
    'manual_intro': 'System Introduction',
    'manual_intro_desc': 'Comprehensive real-time management and monitoring system for 40-foot REEFER refrigerated containers, designed for automated control of fruit ripening processes.',
    
    // Manual Sections
    'section_login': '1. Login',
    'section_login_desc': 'System access through user credentials.',
    'section_dashboard': '2. Dashboard',
    'section_dashboard_desc': 'Fleet overview and operational metrics.',
    'section_device_control': '3. Device Control',
    'section_device_control_desc': 'Individual equipment management in manual mode.',
    'section_device_detail': '4. Device Detail',
    'section_device_detail_desc': 'Complete information and real-time telemetry.',
    'section_monitoring': '5. Monitoring & Analysis',
    'section_monitoring_desc': 'Historical charts and performance metrics.',
    'section_processes': '6. Process Tracking (PLUS)',
    'section_processes_desc': 'Batch management and ripening tracking.',
    'section_recipes': '7. Recipe Library (PLUS)',
    'section_recipes_desc': 'Standardized protocols and custom recipes.',
    'section_recipe_builder': '8. Recipe Builder',
    'section_recipe_builder_desc': 'Step-by-step protocol creation.',
    'section_users': '9. User Management (PLUS)',
    'section_users_desc': 'Account and permissions administration.',
    'section_profile': '10. User Profile',
    'section_profile_desc': 'Personal settings and preferences.',
    
    // Login Section Details
    'login_step1': 'Enter your corporate email address.',
    'login_step2': 'Enter your assigned password.',
    'login_step3': 'Press "Log In" to access the system.',
    'login_note': 'The system will validate your credentials and redirect you to the Dashboard if correct.',
    
    // Dashboard Section Details
    'dashboard_step1': 'View general metrics: Active Units, Alarms, Completed Processes, and Consumption.',
    'dashboard_step2': 'Review each device status through information cards.',
    'dashboard_step3': 'Use the search bar to filter specific devices.',
    'dashboard_step4': 'Click any card to access device details.',
    'dashboard_note': 'Colors indicate status: Green (operational), Orange (warning), Red (alarm), Gray (offline).',
    
    // Device Control Details
    'control_step1': 'Select the device from the Dashboard.',
    'control_step2': 'Verify that the equipment is powered on (top toggle).',
    'control_step3': 'Activate manual control mode.',
    'control_step4': 'Adjust desired parameters: temperature, humidity, ethylene, ventilation.',
    'control_step5': 'Press "Apply Changes" and confirm the operation.',
    'control_note': 'You can only modify parameters if the equipment is on and manual control is active.',
    
    // Device Detail Details
    'detail_step1': 'Access from Dashboard by clicking on a card.',
    'detail_step2': 'The "Operation" tab shows real-time telemetry and manual control.',
    'detail_step3': 'The "Analysis" tab presents historical charts.',
    'detail_step4': 'Use the "Historical Data" button to query specific ranges.',
    'detail_note': 'Data updates automatically every 30 seconds.',
    
    // Monitoring Details
    'monitoring_step1': 'Navigate to "Monitoring & Analysis" from the side menu.',
    'monitoring_step2': 'Select a device to view detailed metrics.',
    'monitoring_step3': 'Configure date range for historical analysis.',
    'monitoring_step4': 'Toggle metrics on/off in charts as needed.',
    'monitoring_note': 'You can export data or generate reports for offline analysis.',
    
    // Processes Details
    'processes_step1': 'Access "Tracking (Plus)" from the menu.',
    'processes_step2': 'View all active batches with their status and progress.',
    'processes_step3': 'Use "New Process" to start a ripening batch.',
    'processes_step4': 'Complete client data, batch info, and select recipe.',
    'processes_step5': 'Assign device and confirm to start.',
    'processes_note': 'The system will automatically track each process phase.',
    
    // Recipes Details
    'recipes_step1': 'Navigate to "Recipes (Plus)" from the menu.',
    'recipes_step2': 'Three system recipes (non-deletable): Avocado, Mango, and Banana, with typical room setpoints. Duplicate to customize.',
    'recipes_step3': 'Click "View Details" to inspect the protocol.',
    'recipes_step4': 'Use "New Recipe" to create custom protocols.',
    'recipes_note': 'Standard recipes are maintained in the catalog; use “Duplicate” for an editable copy. Standard recipes cannot be deleted.',
    
    // Recipe Builder Details
    'builder_step1': 'From "Recipes", press "New Recipe".',
    'builder_step2': 'Enter protocol name and product.',
    'builder_step3': 'Configure each phase in order: Homogenization → Ripening → Venting → Cooling.',
    'builder_step4': 'Define specific parameters for each phase.',
    'builder_step5': 'Save the recipe to use in future processes.',
    'builder_note': 'The phase sequence is mandatory and follows the technical ripening logic.',
    
    // Users Details
    'users_step1': 'Access "Users (Plus)" from the menu.',
    'users_step2': 'View the complete list of system users.',
    'users_step3': 'Use "New User" to add accounts.',
    'users_step4': 'Assign roles (Administrator, Operator, Supervisor).',
    'users_step5': 'Activate or deactivate users as needed.',
    'users_note': 'Only administrators can manage users.',
    
    // Profile Details
    'profile_step1': 'Click on your avatar or name in the header.',
    'profile_step2': 'Update your personal information: name, email, phone.',
    'profile_step3': 'Change your password if needed.',
    'profile_step4': 'Configure preferences: language, theme, temperature units.',
    'profile_note': 'Changes are applied immediately throughout the system.',
  }
};

const defaultContext: SettingsContextType = {
  language: 'es',
  setLanguage: () => {},
  theme: 'light',
  setTheme: () => {},
  tempUnit: 'C',
  toggleTempUnit: () => {},
  displayTimeZone: DEFAULT_DISPLAY_TIMEZONE,
  setDisplayTimeZone: () => {},
  formatDateTime: (input, withSeconds) => formatInDisplayTimeZone(input, DEFAULT_DISPLAY_TIMEZONE, 'es', withSeconds),
  formatDateShort: (input) => formatDateShortInDisplayTimeZone(input, DEFAULT_DISPLAY_TIMEZONE, 'es'),
  formatFileTimestamp: (input) => formatFileTimestampInDisplayTimeZone(input ?? new Date(), DEFAULT_DISPLAY_TIMEZONE),
  convertTemp: (c) => c,
  formatTemp: (c) => `${c}°C`,
  t: (key) => key,
};

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('es');
  const [theme, setThemeState] = useState<Theme>('light');
  const [tempUnit, setTempUnit] = useState<TempUnit>('C');
  const [displayTimeZone, setDisplayTimeZoneState] = useState<string>(DEFAULT_DISPLAY_TIMEZONE);

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    const savedTheme = localStorage.getItem('app_theme') as Theme;
    const savedUnit = localStorage.getItem('app_temp_unit') as TempUnit;
    const savedTz = localStorage.getItem('app_display_timezone')?.trim();

    if (savedLang && (savedLang === 'es' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }

    if (savedTheme && (savedTheme === 'light' || savedTheme === 'dark')) {
      setThemeState(savedTheme);
    } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
       setThemeState('dark');
    }

    if (savedUnit && (savedUnit === 'C' || savedUnit === 'F')) {
      setTempUnit(savedUnit);
    }

    if (savedTz) {
      setDisplayTimeZoneState(savedTz);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const setTheme = (newTheme: Theme) => {
    setThemeState(newTheme);
    localStorage.setItem('app_theme', newTheme);
  };

  const toggleTempUnit = () => {
    const newUnit = tempUnit === 'C' ? 'F' : 'C';
    setTempUnit(newUnit);
    localStorage.setItem('app_temp_unit', newUnit);
  };

  const convertTemp = (celsius: number): number => {
    if (tempUnit === 'C') return celsius;
    return parseFloat(((celsius * 9/5) + 32).toFixed(1));
  };

  const formatTemp = (celsius: number): string => {
    return `${convertTemp(celsius)}°${tempUnit}`;
  };

  const setDisplayTimeZone = (iana: string) => {
    setDisplayTimeZoneState(iana);
    try {
      localStorage.setItem('app_display_timezone', iana);
    } catch {
      /* ignore */
    }
  };

  const formatDateTime = useCallback(
    (input: string | number | Date | null | undefined, withSeconds = false) =>
      formatInDisplayTimeZone(input, displayTimeZone, language, withSeconds),
    [displayTimeZone, language]
  );

  const formatDateShort = useCallback(
    (input: string | number | Date | null | undefined) =>
      formatDateShortInDisplayTimeZone(input, displayTimeZone, language),
    [displayTimeZone, language]
  );

  const formatFileTimestamp = useCallback(
    (input?: string | number | Date) =>
      formatFileTimestampInDisplayTimeZone(input ?? new Date(), displayTimeZone),
    [displayTimeZone]
  );

  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }, [theme]);

  const t = (key: string, replacements?: Record<string, string> | string) => {
    let term = translations[language][key] || key;
    
    if (typeof replacements === 'string') {
        return term === key ? replacements : term;
    }

    if (replacements && typeof replacements === 'object') {
      Object.entries(replacements).forEach(([k, v]) => {
        term = term.replace(`{{${k}}}`, v);
      });
    }
    
    return term;
  };

  return (
    <SettingsContext.Provider
      value={{
        language,
        setLanguage,
        theme,
        setTheme,
        tempUnit,
        toggleTempUnit,
        displayTimeZone,
        setDisplayTimeZone,
        formatDateTime,
        formatDateShort,
        formatFileTimestamp,
        convertTemp,
        formatTemp,
        t,
      }}
    >
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    // Return default context for isolated renders/previews instead of throwing
    return defaultContext;
  }
  return context;
};